### ISSUE TITLE
Update nsd AMI for 20sp

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/nsd#14]

**Comment by tigercosmos** [comment]
老師下學期還有開！

**Comment by yungyuc** [comment]
Yes, and I still need a TA.  Do you want to do it again?

**Comment by yungyuc** [comment]
done

**Comment by tigercosmos** [comment]
@yungyuc yes. practice makes better. XD

**Comment by yungyuc** [comment]
@tigercosmos OK let me ask the office.
