### ISSUE TITLE
Add more information on README

### ISSUE THREAD

**Issue by tigercosmos** [yungyuc/nsd#21]
With more information on README, it would probably be easier to share this course on the Internet. cc @yungyuc

**Comment by yungyuc** [comment]
Sounds good.  What information is good to add?

**Comment by tigercosmos** [comment]
maybe copy the [notebook](https://github.com/yungyuc/nsd/blob/master/notebook/20au_nctu/index.ipynb) content to README?
Then we can use Github Page to render the repo's readme as a website just like https://nctu-sslab.github.io/Parallel-Programming-Fall-2020/ does.

**Comment by yungyuc** [comment]
I think it's good to copy some of the information from the notebook front page to the repository front page (README).

I will add things to the notes during the semester and the table of contents of each lecture is likely to change.  Lecture schedule could also change for unexpected events.  I'd like to keep those changes in one place, so perhaps we should not copy them.

Could you please make a list for what may be copied?  A PR works too.
