### ISSUE TITLE
[Lecture 12] There are "unknown character" in formula

### ISSUE THREAD

**Issue by TommyLin** [yungyuc/nsd#30]
In [Lecture 12 Array code in C++](https://github.com/yungyuc/nsd/blob/master/notebook/20au_nctu/12_arraycode/arraycode.ipynb), there are "unknown character" in document. Such as:
![Formula](https://render.githubusercontent.com/render/math?math=%5Cbegin%7Balign%7D%0A%25%0Au%5E%7Bn%2B1%7D%28x_i%2C%20y_i%29%20%3D%20%5Cfrac%7Bu%5En%28x_%7Bi%2B1%7D%2C%20y_j%29%20%2B%20u%5En%28x_%7Bi-1%7D%2C%20y_j%29%20%2B%20u%5En%28x_i%2C%20y_%7Bj%2B1%7D%29%20%2B%20u%5En%28x_i%2C%20y_%7Bj-1%7D%29%7D%7B4%7D%0A%25%0A%5Cend%7Balign%7D)

**Comment by yungyuc** [comment]
It looks like an issue on the GitHub side.  When I view the notebook in jupyter, the rendering is OK:

<img width="616" alt="Screen Shot 2020-12-07 at 17 50 54" src="https://user-images.githubusercontent.com/399122/101335918-c4165a00-38b4-11eb-9bab-c162342b8867.png">
